export const Keys = {
  SPACE: ' ',
  SHIFT: 'Shift',
  CTRL: 'Control',
  ALT: 'Alt',
  META: 'Meta',
  ENTER: 'Enter',
  TAB: 'Tab',
  ESCAPE: 'Escape',
  BACKSPACE: 'Backspace',
  FORWARD_SLASH: '/',
  PIPE: '|',
  DASH: '-',
} as const;

export const topLevelMappings = [
  {
    prefix: [Keys.SPACE],
    name: 'Open Quick Switcher',
    id: 'switcher:open',
    icon: 'square-chevron-right',
  },
  {
    prefix: [Keys.FORWARD_SLASH],
    name: 'Open Global Search',
    id: 'global-search:open',
    icon: 'globe',
  },
  {
    prefix: ['e'],
    name: 'Toggle left sidebar',
    id: 'app:toggle-left-sidebar',
    icon: 'panel-left',
  },
  {
    prefix: ['p'],
    name: 'Open command palette',
    id: 'command-palette:open',
    icon: 'square-terminal',
  },
  {
    prefix: [Keys.PIPE],
    name: 'Split right',
    id: 'workspace:split-vertical',
    icon: 'separator-vertical',
  },
  {
    prefix: [Keys.DASH],
    name: 'Split down',
    id: 'workspace:split-horizontal',
    icon: 'separator-horizontal',
  },
];

export const intentMappings = [
  {
    prefix: ['s'],
    name: 'Search',
    id: undefined,
    icon: 'search',
    pattern: /^(?!.*bookmark).*(search|switcher|command-palette)/,
  },
  {
    prefix: ['f'],
    name: 'File',
    id: undefined,
    icon: 'file',
    pattern: /^(?!.*canvas).*(file|attach|template|properties|zk-prefixer)/,
  },
  {
    prefix: ['l'],
    name: 'Links',
    id: undefined,
    icon: 'link',
    pattern: /link/,
  },
  {
    prefix: ['b'],
    name: 'Bookmarks',
    id: undefined,
    icon: 'bookmark',
    pattern: /bookmarks/,
  },
  {
    prefix: [Keys.TAB],
    name: 'Tab navigation',
    id: undefined,
    icon: 'arrow-right-to-line',
    pattern: /^(?!.*(table|tag)).*(tab|pane|pin|workspace:close|editor:focus)/,
  },
  {
    prefix: ['v'],
    name: 'Vault',
    id: undefined,
    icon: 'vault',
    pattern: /vault/,
  },
  {
    prefix: ['t'],
    name: 'Text',
    id: undefined,
    icon: 'text',
    pattern:
      /(?=.*editor)(?=.*toggle)|heading|clear-formatting|cycle-list-checklist|swap-line|add-cursor|delete-paragraph|context-menu|fold|formatting/,
    // /(?:editor:toggle|heading|clear-formatting|cycle-list-checklist|swap-line|add-cursor|delete-paragraph|context-menu|fold(?!.*file))/,
  },
  {
    prefix: ['T'],
    name: 'Table',
    id: undefined,
    icon: 'table',
    pattern: /table/,
  },
  {
    prefix: ['n'],
    name: 'Navigate',
    id: undefined,
    icon: 'navigation',
    pattern: /app:go-(?:back|forward)$/,
  },
  {
    prefix: ['m'],
    name: 'Markdown',
    id: undefined,
    icon: 'a-large-small',
    pattern: /markdown/,
  },
  {
    prefix: ['w'],
    name: 'Windows',
    id: undefined,
    icon: 'app-window',
    pattern: /(?:window|workspaces|sidebar|split)/,
  },
  {
    prefix: ['u'],
    name: 'UI',
    id: undefined,
    icon: 'palette',
    pattern: /theme/,
  },
  {
    prefix: ['a'],
    name: 'App',
    id: undefined,
    icon: 'dock',
    pattern:
      /(?:app(?!.*(?:vault|go))|export(?!.*canvas)|workspace:(?:show-trash|copy)|editor:focus|tag-pane|outline|random-note|slides|audio-recorder)/,
  },
  {
    prefix: ['i'],
    name: 'Insert',
    id: undefined,
    icon: 'between-horizontal-start',
    pattern: /insert/,
  },

  // Core Plugins
  // TODO: These need to be conditionally shown if the patter matches
  {
    prefix: ['c'],
    name: 'Canvas',
    id: undefined,
    icon: 'brush',
    pattern: /canvas/,
  },
  {
    prefix: ['d'],
    name: 'Daily Notes',
    id: undefined,
    icon: 'calendar',
    pattern: /daily-notes/,
  },
  {
    prefix: ['g'],
    name: 'Graph',
    id: undefined,
    icon: 'brain-circuit',
    pattern: /graph(?!.*editor)/,
  },
  {
    prefix: ['S'],
    name: 'Sync',
    id: undefined,
    icon: 'folder-sync',
    pattern: /sync/,
  },
  {
    prefix: ['W'],
    name: 'Webviewer',
    id: undefined,
    icon: 'globe',
    pattern: /webviewer/,
  },
  {
    prefix: ['M'],
    name: 'Miscellaneous',
    id: undefined,
    icon: 'circle-help',
    pattern: /.*/,
  },
];
