export const KEYS = {
  SPACE: ' ',
  SHIFT: 'Shift',
  CTRL: 'Control',
  ALT: 'Alt',
  META: 'Meta',
  ENTER: 'Enter',
  TAB: 'Tab',
  ESCAPE: 'Escape',
  BACKSPACE: 'Backspace',
  FORWARD_SLASH: '/',
  PIPE: '|',
  DASH: '-',
} as const;

/** For categorizing commands by intent */
export const intentRegexes = {
  a: /^(?!.*(canvas|vault|toggle-ribbon|app:go)).*(app|audio|slides|publish|workspace:copy)/,
  b: /bookmarks/,
  c: /canvas/,
  d: /daily-notes/,
  f: /^(?!.*canvas).*(file|attach|template|export-pdf|show-trash|zk-prefixer)/,
  g: /^(?!.*editor).*graph/,
  i: /insert/,
  l: /link/,
  m: /markdown|properties/,
  n: /(?:app:go-(?:back|forward)|outline)/,
  s: /^(?!.*bookmark).*(search|switcher|command-palette)/,
  S: /sync/,
  t: /(?=.*editor)(?=.*toggle)|heading|cycle-list-checklist|swap-line|add-cursor|delete-paragraph|context-menu|fold|formatting/,
  T: /table/,
  Tab: /^(?!.*(table|tag)).*(tab|pane|pin|workspace:close|editor:focus)/,
  u: /theme/,
  v: /vault/,
  w: /window|workspaces|sidebar|split|toggle-ribbon|tag-pane|outline/,
  W: /webviewer/,
};

export const topLevelMappings = [
  {
    prefix: [KEYS.SPACE],
    name: 'Open Quick Switcher',
    id: 'switcher:open',
    icon: 'square-chevron-right',
  },
  {
    prefix: [KEYS.FORWARD_SLASH],
    name: 'Open Global Search',
    id: 'global-search:open',
    icon: 'globe',
  },
  {
    prefix: ['e'],
    name: 'Toggle left sidebar',
    id: 'app:toggle-left-sidebar',
    icon: 'panel-left',
  },
  {
    prefix: ['p'],
    name: 'Open command palette',
    id: 'command-palette:open',
    icon: 'square-terminal',
  },
  {
    prefix: [KEYS.PIPE],
    name: 'Split right',
    id: 'workspace:split-vertical',
    icon: 'separator-vertical',
  },
  {
    prefix: [KEYS.DASH],
    name: 'Split down',
    id: 'workspace:split-horizontal',
    icon: 'separator-horizontal',
  },
];

export const intentMappings = [
  {
    prefix: ['a'],
    name: 'App',
    id: undefined,
    icon: 'dock',
    pattern: intentRegexes.a,
  },
  {
    prefix: ['b'],
    name: 'Bookmarks',
    id: undefined,
    icon: 'bookmark',
    pattern: intentRegexes.b,
  },
  {
    prefix: ['c'],
    name: 'Canvas',
    id: undefined,
    icon: 'brush',
    pattern: intentRegexes.c,
  },
  {
    prefix: ['d'],
    name: 'Daily Notes',
    id: undefined,
    icon: 'calendar',
    pattern: intentRegexes.d,
  },
  {
    prefix: ['f'],
    name: 'File',
    id: undefined,
    icon: 'file',
    pattern: intentRegexes.f,
  },
  {
    prefix: ['g'],
    name: 'Graph',
    id: undefined,
    icon: 'brain-circuit',
    pattern: intentRegexes.g,
  },
  {
    prefix: ['i'],
    name: 'Insert',
    id: undefined,
    icon: 'between-horizontal-start',
    pattern: intentRegexes.i,
  },
  {
    prefix: ['l'],
    name: 'Links',
    id: undefined,
    icon: 'link',
    pattern: intentRegexes.l,
  },
  {
    prefix: ['m'],
    name: 'Markdown',
    id: undefined,
    icon: 'a-large-small',
    pattern: intentRegexes.m,
  },
  {
    prefix: ['n'],
    name: 'Navigate',
    id: undefined,
    icon: 'navigation',
    pattern: intentRegexes.n,
  },
  {
    prefix: ['s'],
    name: 'Search',
    id: undefined,
    icon: 'search',
    pattern: intentRegexes.s,
  },
  {
    prefix: ['S'],
    name: 'Sync',
    id: undefined,
    icon: 'folder-sync',
    pattern: intentRegexes.S,
  },
  {
    prefix: ['t'],
    name: 'Text',
    id: undefined,
    icon: 'text',
    pattern: intentRegexes.t,
  },
  {
    prefix: ['T'],
    name: 'Table',
    id: undefined,
    icon: 'table',
    pattern: intentRegexes.T,
  },
  {
    prefix: [KEYS.TAB],
    name: 'Tab navigation',
    id: undefined,
    icon: 'arrow-right-to-line',
    pattern: intentRegexes.Tab,
  },
  {
    prefix: ['u'],
    name: 'UI',
    id: undefined,
    icon: 'palette',
    pattern: intentRegexes.u,
  },
  {
    prefix: ['v'],
    name: 'Vault',
    id: undefined,
    icon: 'vault',
    pattern: intentRegexes.v,
  },
  {
    prefix: ['w'],
    name: 'Windows',
    id: undefined,
    icon: 'app-window',
    pattern: intentRegexes.w,
  },
  {
    prefix: ['W'],
    name: 'Webviewer',
    id: undefined,
    icon: 'globe',
    pattern: intentRegexes.W,
  },
];
