name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    uses: ./.github/workflows/shared-build.yml

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create $tag \
            --generate-notes \
            --title $tag \
            --draft \
            main.js manifest.json styles.css
